version: '3'

services:
    blockchain_messenger:
        container_name: blockchain-messenger
        hostname: blockchain-messenger
        restart: always
        build:
          context: .
        volumes:
            - ./:/opt
        ports:
            - "4200:4200"
        stdin_open: true
        dns:
          - 8.8.8.8
          - 9.9.9.9
        expose:
          - "4200"
        command: bash /opt/run.sh
        networks:
          - overlay
networks:
    overlay:
